sidebar:
  entries:
    - title: NetApp Solutions Documentation
      url: /index.html
    - section: ai-mda
    - section: hybrid-cloud
    - section: ea-db
    - section: dp-sec
    - section: infra
    - section: automation
    - title: Change Log
      url: /change-log.html

homepage:
  tiles:
    - title: AI & Modern Data Analytics
      links:
        - title: "NEW: NetApp ONTAP AI with NVIDIA DGX A100 Systems Design Guide"
          url: https://www.netapp.com/pdf.html?item=/media/19432-nva-1151-design.pdf
        - title: "NEW: NetApp ONTAP AI with NVIDIA DGX A100 Systems Deployment Guide"
          url: https://www.netapp.com/pdf.html?item=/media/20708-nva-1151-deploy.pdf
        - title: "NEW: AI Orchestration with NetApp and Run:AI"
          url: https://www.netapp.com/pdf.html?item=/media/19505-TR-4858.pdf
        - title: "NEW: NetApp Data Science Toolkit"
          url: https://github.com/NetApp/netapp-data-science-toolkit
        - title: "VIDEOS: NetApp AI Solutions"
          url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7nSrRhuolRPYqvSlGLuTOAO
        - title: "VIDEOS: MLOps"
          url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7n1sWK-QGq4QMI1VBJS-ZZW
        - title: "BLOGS: NetApp.com"
          url: https://blog.netapp.com/tag/artificial-intelligence/
        - title: "BLOGS: thePub"
          url: https://netapp.io/category/ai-ml/

    - title: Hybrid Cloud
      links:
        - title: "NEW: Hybrid Cloud VDI with NetApp Virtual Desktop Service"
          summary: NetApp Virtual Desktop Service (VDS) orchestrates Remote Desktop Services (RDS) in major public clouds as well as on private clouds
          url: /hcvdivds_hybrid_cloud_vdi_with_virtual_desktop_service.html
        - title: "NEW: Anthos on Bare Metal with NetApp"
          summary: NetApp ONTAP with Google Cloud Anthos on bare metal
          url: https://www.netapp.com/pdf.html?item=/media/21072-wp-7337.pdf


    - title: Enterprise Applications & Databases
      links:
        - title: "NEW: Deploying MSSQL Database Workloads on NetApp HCI"
          summary: Why NetApp HCI is best suited for hosting MSSQL workloads
          url: https://www.netapp.com/pdf.html?item=/media/20648-tr-4870.pdf
        - title: "NEW: ESG Technical Validation: Assuring Database Performance and Availability with NetApp HCI"
          summary: Third-party study on assurance of database performance on NetApp HCI
          url: https://www.esg-global.com/validation/esg-technical-validation-assuring-database-performance-and-availability-with-netapp-hci

    - title: Data Protection & Security
      links:

    - title: Infrastructure
      links:
        - title: "NEW: eSDS NetApp SolidFire Enterprise SDS Running Microsoft SQL Server and Virtualized Infrastructure"
          summary: Overview of NetApp SolidFire SDS offering for database workloads
          url: https://www.netapp.com/pdf.html?item=/media/20030-tr-4866.pdf
        - title: "NEW: Guaranteeing Mixed-workload Performance and NetApp HCI"
          summary: Third-party assurance of mulitpe workload performance on NetApp HCI
          url: https://www.esg-global.com/validation/esg-technical-validation-guaranteeing-mixed-workload-performance-with-netapp-hci

    - title: Solution Automation
      links:
