sidebar:
  entries:
    - title: NetApp Solutions Documentation
      url: /index.html
    - section: ai
    - section: data-analytics
    - section: hybrid-cloud
    - section: vdi-vds
    - section: containers
    - section: biz-apps
    - section: ent-db
    - section: dp-sec
    - section: infra
    - section: automation
    - title: Change Log
      url: /change-log.html

homepage:
  tiles:
    - title: AI & Modern Data Analytics
      links:
        - title: "What's New"
          summary: Check out the latest AI and Modern Data Analytics solutions
          url: aimda-whatsnew.html
        - title: "NetApp Data Science toolkit"
          summary:
          url: https://github.com/NetApp/netapp-data-science-toolkit
        - title: "Videos and Demos"
          summary: Short videos / demos for AI and Modern Data Analytics features
          url: aimda-video.html
        - title: "Blogs"
          summary: Technical blogs highlighting AI and Modern Data Analytics features
          url: aimda-blogs.html
#
    - title: Hybrid Cloud, Virtualization & Containers
      links:
        - summary: "<b>What's New?</b>"
        - title: "Hybrid Cloud VDI with NetApp Virtual Desktop Service"
          summary: NetApp Virtual Desktop Service (VDS) orchestrates Remote Desktop Services (RDS) in major public clouds as well as on private clouds
          url: /hcvdivds_hybrid_cloud_vdi_with_virtual_desktop_service.html
        - title: "Anthos on Bare Metal with NetApp"
          summary: NetApp ONTAP with Google Cloud Anthos on bare metal
          url: https://www.netapp.com/pdf.html?item=/media/21072-wp-7337.pdf
#
    - title: Business Applications & Enterprise Databases
      links:
        - title: "What's New"
          summary: Check out the latest Business Applications & Enterprise Database solutions
          url: appsdb-whatsnew.html
        - title: "Videos and Demos"
          summary: Short videos / demos for Business Applications & Enterprise Database features
          url: appsdb-video.html
        - title: "Blogs"
          summary: Technical blogs highlighting Business Applications & Enterprise Database features
          url: appsdb-blogs.html
#
    - title: Data Protection & Security
      links:
        - summary: "<b>What's New?</b>"
        - title: "NetApp HCI Verified Architecture for PCI-DSS"
          summary: Third party whitepaper defining the validation of NetApp HCI as a PCI-DSS platform.
          url: https://www.coalfire.com/resources/white-papers/netapp-hci-verified-architecture-for-pci-dss

    - title: Solution Automation
      links:
        - summary: "<b>What's New?</b>"
          summary: COMING SOON!
